services:
  - type: web
    name: baby-cry-detector
    env: python
    buildCommand: "sh build.sh"
    startCommand: "gunicorn crybaby.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: CRY_DETECTION_API_KEY
        value: "dev-api-key-change-in-production"
