services:
  - type: web
    name: baby-cry-detector
    env: python
    region: ohio
    plan: starter
    buildCommand: "sh build.sh"
    startCommand: "gunicorn crybaby.wsgi --workers 2 --threads 4 --timeout 120"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: CRY_DETECTION_API_KEY
        value: "dev-api-key-change-in-production"
